const DEFAULT_COMBINED_SCANNER_WIDTH_IN = 24;
const DEFAULT_SINGLE_SCANNER_WIDTH_IN = 20;

export const APP_CONFIG = Object.freeze({
    SVG_NS: 'http://www.w3.org/2000/svg',
    SCAN_PADDING_PX: 10,
    SCAN_DRAW_WIDTH_PX: 480,
    SCAN_DRAW_HEIGHT_PX: 400,
    COVERAGE_DRAW_SIZE_PX: 400,
    PLANT_VISUAL_MAGNIFICATION: 2,
    SPEED_CAP_MPH: 3,
    MAX_SHOTS_PER_STEP_PER_SCANNER: 6,
    CENTER_PRIORITY_MIN_WIDTH_IN: 3,
    CENTER_PRIORITY_OVERLOAD_GAIN: 0.5,
    CENTER_PRIORITY_ACTIVATION_RATIO: 1.02,
    BROADLEAF_LEAF_PATH: 'M0,0 Q-0.22,-0.45 0,-1 Q0.22,-0.45 0,0',
    GRASS_LEAF_PATH: 'M0,0 L-0.08,0 L0,-1 L0.08,0 Z',
    DEFAULT_DENSITY_PER_SQFT: 60,
    DEFAULT_WEED_SIZE: 10,
    INITIAL_BAND_WIDTH_IN: DEFAULT_COMBINED_SCANNER_WIDTH_IN,
    INITIAL_SCANNER_A_RIGHT_IN: DEFAULT_SINGLE_SCANNER_WIDTH_IN,
    INITIAL_SCANNER_B_LEFT_IN: DEFAULT_COMBINED_SCANNER_WIDTH_IN - DEFAULT_SINGLE_SCANNER_WIDTH_IN,
    DEFAULT_OVERHEAD_MS: 60,
    DEFAULT_SPEED_UTILIZATION_PERCENT: 99,
    DEFAULT_TARGETING_POLICY: 'bottom',
    DEFAULT_TARGET_MIDLINE_Y_IN: 10,
    DEFAULT_TARGET_URGENT_Y_IN: 16,
    DEFAULT_MACHINE_WIDTH_FT: 20,
    DEFAULT_FIELD_AREA_ACRES: 40,
    DEFAULT_FIELD_SHAPE: 'square',
    DEFAULT_FIELD_EFFICIENCY_PERCENT: 80,
    DEFAULT_COVERAGE_TIME_HOURS: 1
});
