function requireElement(id) {
    const element = document.getElementById(id);
    if (!element) {
        throw new Error(`Missing required DOM element: #${id}`);
    }
    return element;
}

export function getDomRefs() {
    return {
        addWeedCategoryButton: requireElement('add-weed-category-button'),
        weedCategoryList: requireElement('weed-category-list'),
        bandWidthSlider: requireElement('band-width-slider'),
        scannerAEndSlider: requireElement('scanner-a-end-slider'),
        scannerBStartSlider: requireElement('scanner-b-start-slider'),
        overheadSlider: requireElement('overhead-slider'),
        speedUtilizationSlider: requireElement('speed-utilization-slider'),
        targetingPolicySelect: requireElement('targeting-policy-select'),
        targetMidlineSlider: requireElement('target-midline-slider'),
        targetUrgentSlider: requireElement('target-urgent-slider'),
        machineWidthInput: requireElement('machine-width-input'),
        fieldAreaInput: requireElement('field-area-input'),
        fieldShapeSelect: requireElement('field-shape-select'),
        coverageEfficiencySlider: requireElement('coverage-efficiency-slider'),
        coverageHoursSlider: requireElement('coverage-hours-slider'),

        totalDensityValue: requireElement('total-density-value'),
        bandWidthValue: requireElement('band-width-value'),
        scannerAEndValue: requireElement('scanner-a-end-value'),
        scannerBStartValue: requireElement('scanner-b-start-value'),
        overheadValue: requireElement('overhead-value'),
        speedUtilizationValue: requireElement('speed-utilization-value'),
        targetMidlineValue: requireElement('target-midline-value'),
        targetUrgentValue: requireElement('target-urgent-value'),
        windowDensity: requireElement('window-density'),
        coverageEfficiencyValue: requireElement('coverage-efficiency-value'),
        coverageHoursValue: requireElement('coverage-hours-value'),

        runButton: requireElement('run-button'),
        pauseButton: requireElement('pause-button'),
        resetButton: requireElement('reset-button'),
        recordPassButton: requireElement('record-pass-button'),
        resetDefaultsButton: requireElement('reset-defaults-button'),

        metricsTabSimulation: requireElement('metrics-tab-simulation'),
        metricsTabCoverage: requireElement('metrics-tab-coverage'),
        metricsPanelSimulation: requireElement('metrics-panel-simulation'),
        metricsPanelSimulationSecondary: requireElement('metrics-panel-simulation-secondary'),
        metricsPanelCoverage: requireElement('metrics-panel-coverage'),
        simulationVisualView: requireElement('simulation-visual-view'),
        coverageVisualView: requireElement('coverage-visual-view'),

        appliedSpeedMph: requireElement('applied-speed-mph'),
        speedCapNote: requireElement('speed-cap-note'),

        densityReadout: requireElement('density-readout'),
        bandedShareReadout: requireElement('banded-share-readout'),
        bandedShareFill: requireElement('banded-share-fill'),
        bandWidthReadout: requireElement('band-width-readout'),
        coverageReadout: requireElement('coverage-readout'),
        coverageGapReadout: requireElement('coverage-gap-readout'),
        coverageWarning: requireElement('coverage-warning'),
        inflowReadout: requireElement('inflow-readout'),
        capacityReadout: requireElement('capacity-readout'),
        activeTargetsReadout: requireElement('active-targets-readout'),
        queueDepthReadout: requireElement('queue-depth-readout'),
        shotsReadout: requireElement('shots-readout'),
        shotsPerSecondReadout: requireElement('shots-per-second-readout'),
        shotsPerMinuteReadout: requireElement('shots-per-minute-readout'),
        shotsPerHourReadout: requireElement('shots-per-hour-readout'),
        missedReadout: requireElement('missed-readout'),
        partialReadout: requireElement('partial-readout'),
        hitRateReadout: requireElement('hit-rate-readout'),
        shotLineReadout: requireElement('shot-line-readout'),
        shotMarginReadout: requireElement('shot-margin-readout'),
        queueGrowthReadout: requireElement('queue-growth-readout'),
        categoryMetricsBody: requireElement('category-metrics-body'),
        scannerAUtilReadout: requireElement('scanner-a-util-readout'),
        scannerBUtilReadout: requireElement('scanner-b-util-readout'),
        scannerADutyReadout: requireElement('scanner-a-duty-readout'),
        scannerBDutyReadout: requireElement('scanner-b-duty-readout'),
        elapsedReadout: requireElement('elapsed-readout'),
        recordPassStatus: requireElement('record-pass-status'),
        passSnapshotHistory: requireElement('pass-snapshot-history'),
        snapshotDetailModal: requireElement('snapshot-detail-modal'),
        snapshotDetailBackdrop: requireElement('snapshot-detail-backdrop'),
        snapshotDetailDialog: requireElement('snapshot-detail-dialog'),
        snapshotDetailClose: requireElement('snapshot-detail-close'),
        snapshotDetailTitle: requireElement('snapshot-detail-title'),
        snapshotDetailSettings: requireElement('snapshot-detail-settings'),
        snapshotDetailCounts: requireElement('snapshot-detail-counts'),
        snapshotDetailScroll: requireElement('snapshot-detail-scroll'),
        snapshotDetailPlot: requireElement('snapshot-detail-plot'),

        rawSpeedReadout: requireElement('raw-speed-readout'),
        utilizedSpeedReadout: requireElement('utilized-speed-readout'),
        appliedSpeedReadout: requireElement('applied-speed-readout'),
        utilizationTargetReadout: requireElement('utilization-target-readout'),
        shootTimeReadout: requireElement('shoot-time-readout'),
        overheadReadout: requireElement('overhead-readout'),
        timePerTargetReadout: requireElement('time-per-target-readout'),
        targetingPolicyReadout: requireElement('targeting-policy-readout'),
        overloadRatioReadout: requireElement('overload-ratio-readout'),
        centerPriorityActiveReadout: requireElement('center-priority-active-readout'),
        centerPriorityWidthReadout: requireElement('center-priority-width-readout'),
        targetMidlineReadout: requireElement('target-midline-readout'),
        targetUrgentReadout: requireElement('target-urgent-readout'),
        scannerARangeReadout: requireElement('scanner-a-range-readout'),
        scannerBRangeReadout: requireElement('scanner-b-range-readout'),

        coverageSpeedReadout: requireElement('coverage-speed-readout'),
        coverageTravelFpsReadout: requireElement('coverage-travel-fps-readout'),
        coverageRateSqFtHourReadout: requireElement('coverage-rate-sqft-hour-readout'),
        coverageRateAcresHourReadout: requireElement('coverage-rate-acres-hour-readout'),
        coverageFieldAreaReadout: requireElement('coverage-field-area-readout'),
        coverageFieldWidthReadout: requireElement('coverage-field-width-readout'),
        coverageHoursToFinishReadout: requireElement('coverage-hours-to-finish-readout'),
        coverageCoveredAreaReadout: requireElement('coverage-covered-area-readout'),
        coveragePercentReadout: requireElement('coverage-percent-readout'),
        coveragePassesReadout: requireElement('coverage-passes-readout'),
        coverageActivePassReadout: requireElement('coverage-active-pass-readout'),

        visualMachineWidthReadout: requireElement('visual-machine-width-readout'),
        visualFieldReadout: requireElement('visual-field-readout'),
        visualRateReadout: requireElement('visual-rate-readout'),
        visualCompletionReadout: requireElement('visual-completion-readout'),

        gridLayer: requireElement('grid-layer'),
        bandLayer: requireElement('band-layer'),
        zoneLayer: requireElement('zone-layer'),
        weedLayer: requireElement('weed-layer'),
        coverageFieldLayer: requireElement('coverage-field-layer')
    };
}
